# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooteru/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooteru/proprietary/lib/hw/camera.vendor.msm8660.so:obj/lib/hw/camera.vendor.msm8660.so \
    vendor/htc/shooteru/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooteru/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shooteru/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \

# All the blobs necessary for shooteru
PRODUCT_COPY_FILES += \
    vendor/htc/shooteru/proprietary/bin/ipd:system/bin/ipd \
    vendor/htc/shooteru/proprietary/bin/3D_calibration:system/bin/3D_calibration \
    vendor/htc/shooteru/proprietary/bin/3D_calibration_main:system/bin/3D_calibration_main \
    vendor/htc/shooteru/proprietary/bin/charging:system/bin/charging \
    vendor/htc/shooteru/proprietary/bin/htcbatt:system/bin/htcbatt \
    vendor/htc/shooteru/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/htc/shooteru/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/shooteru/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/htc/shooteru/proprietary/bin/snd3254:system/bin/snd3254 \
    vendor/htc/shooteru/proprietary/bin/wireless_modem:system/bin/wireless_modem \
    vendor/htc/shooteru/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/shooteru/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/egl/libGLESv2S3D_adreno200.so:/system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/shooteru/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/htc/shooteru/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/htc/shooteru/proprietary/lib/libc2d2_z180.so:/system/lib/libc2d2_z180.so \
    vendor/htc/shooteru/proprietary/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
    vendor/htc/shooteru/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/htc/shooteru/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
    vendor/htc/shooteru/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/shooteru/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/shooteru/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/htc/shooteru/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/htc/shooteru/proprietary/lib/libaudcalwb.so:system/lib/libaudcalwb.so \
    vendor/htc/shooteru/proprietary/lib/libaudcal_nel.so:system/lib/libaudcal_nel.so \
    vendor/htc/shooteru/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/htc/shooteru/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    vendor/htc/shooteru/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/htc/shooteru/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/htc/shooteru/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/htc/shooteru/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/htc/shooteru/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/htc/shooteru/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/htc/shooteru/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/htc/shooteru/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/htc/shooteru/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/shooteru/proprietary/lib/hw/camera.vendor.msm8660.so:system/lib/hw/camera.vendor.msm8660.so \
    vendor/htc/shooteru/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/shooteru/proprietary/lib/libcameraLN.so:system/lib/libcameraLN.so \
    vendor/htc/shooteru/proprietary/lib/libcameraSP.so:system/lib/libcameraSP.so \
    vendor/htc/shooteru/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/shooteru/proprietary/lib/libchromatix_qs_s5k4e1_preview.so:system/lib/libchromatix_qs_s5k4e1_preview.so \
    vendor/htc/shooteru/proprietary/lib/libchromatix_qs_s5k4e1_video.so:system/lib/libchromatix_qs_s5k4e1_video.so \
    vendor/htc/shooteru/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/htc/shooteru/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/shooteru/proprietary/lib/liboemcamera_main.so:system/lib/liboemcamera_main.so \
    vendor/htc/shooteru/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/htc/shooteru/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
    vendor/htc/shooteru/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/htc/shooteru/proprietary/lib/libgemini2.so:system/lib/libgemini2.so \
    vendor/htc/shooteru/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/htc/shooteru/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/shooteru/proprietary/lib/libmmjpeg2.so:system/lib/libmmjpeg2.so \
    vendor/htc/shooteru/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/htc/shooteru/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
    vendor/htc/shooteru/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/shooteru/proprietary/lib/libmpl.so:system/lib/libmpl.so \
    vendor/htc/shooteru/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/htc/shooteru/proprietary/lib/hw/sensors.shooteru.so:/system/lib/hw/sensors.shooteru.so \
    vendor/htc/shooteru/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so
 
# Firmwares
PRODUCT_COPY_FILES += \
    vendor/htc/shooteru/proprietary/firmware/modem.b00:/system/vendor/firmware/modem.b00 \
    vendor/htc/shooteru/proprietary/firmware/modem.b01:/system/vendor/firmware/modem.b01 \
    vendor/htc/shooteru/proprietary/firmware/modem.b02:/system/vendor/firmware/modem.b02 \
    vendor/htc/shooteru/proprietary/firmware/modem.b03:/system/vendor/firmware/modem.b03 \
    vendor/htc/shooteru/proprietary/firmware/modem.b04:/system/vendor/firmware/modem.b04 \
    vendor/htc/shooteru/proprietary/firmware/modem.b05:/system/vendor/firmware/modem.b05 \
    vendor/htc/shooteru/proprietary/firmware/modem.b06:/system/vendor/firmware/modem.b06 \
    vendor/htc/shooteru/proprietary/firmware/modem.b07:/system/vendor/firmware/modem.b07 \
    vendor/htc/shooteru/proprietary/firmware/modem.b08:/system/vendor/firmware/modem.b08 \
    vendor/htc/shooteru/proprietary/firmware/modem.b09:/system/vendor/firmware/modem.b09 \
    vendor/htc/shooteru/proprietary/firmware/modem.mdt:/system/vendor/firmware/modem.mdt \
    vendor/htc/shooteru/proprietary/firmware/q6.b00:/system/vendor/firmware/q6.b00 \
    vendor/htc/shooteru/proprietary/firmware/q6.b01:/system/vendor/firmware/q6.b01 \
    vendor/htc/shooteru/proprietary/firmware/q6.b02:/system/vendor/firmware/q6.b02 \
    vendor/htc/shooteru/proprietary/firmware/q6.b03:/system/vendor/firmware/q6.b03 \
    vendor/htc/shooteru/proprietary/firmware/q6.b04:/system/vendor/firmware/q6.b04 \
    vendor/htc/shooteru/proprietary/firmware/q6.b05:/system/vendor/firmware/q6.b05 \
    vendor/htc/shooteru/proprietary/firmware/q6.b06:/system/vendor/firmware/q6.b06 \
    vendor/htc/shooteru/proprietary/firmware/q6.b07:/system/vendor/firmware/q6.b07 \
    vendor/htc/shooteru/proprietary/firmware/q6.mdt:/system/vendor/firmware/q6.mdt
